language: node_js
node_js:
  - "8"
script:
    - npm run e2e
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install
notifications:
  email: false
sudo: required
addons:
  chrome: stable
