language: node_js
node_js:
  - "5"
  - "4"
  - "4.4"
script:
    - node_modules/karma/bin/karma start karma.conf.js --single-run
    - node_modules/typescript/bin/tsc -p .
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install
